services:
  db:
    image: postgres:14
    container_name: examen_db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: examenfinal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d examenfinal"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: examen_app
    command: >
      sh -c "uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://usuario:contraseña@db:5432/examenfinal
      PYTHONPATH: /app
    restart: unless-stopped
  
  test:
    build: .
    container_name: currency_exchange_tests
    environment:
      DATABASE_URL: postgresql://usuario:contraseña@db:5432/examenfinal
      PYTHONPATH: /app 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: pytest

volumes:
  postgres_data:
